# Generated by Django 4.2.4 on 2023-08-26 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import panel.models.portfolio


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("panel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theme", models.CharField(max_length=16)),
                ("linkedin_id", models.CharField(max_length=64)),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                ("occupation", models.CharField(blank=True, max_length=256)),
                ("headline", models.CharField(blank=True, max_length=256)),
                ("country", models.CharField(blank=True, max_length=2)),
                ("city", models.CharField(blank=True, max_length=64)),
                ("state", models.CharField(blank=True, max_length=64)),
                ("gender", models.CharField(blank=True, max_length=32)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("industry", models.CharField(blank=True, max_length=64)),
                ("summary", models.TextField(blank=True)),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True, upload_to=panel.models.portfolio.pfp_upload_path
                    ),
                ),
                ("source_url", models.URLField()),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="portfolio",
                        to="sites.site",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="portfolioarticle",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="panel.portfolio"
            ),
        ),
        migrations.AlterField(
            model_name="portfoliocertification",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="panel.portfolio"
            ),
        ),
        migrations.AlterField(
            model_name="portfoliocourse",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="panel.portfolio"
            ),
        ),
        migrations.AlterField(
            model_name="portfolioeducation",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="panel.portfolio"
            ),
        ),
        migrations.AlterField(
            model_name="portfolioexperience",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="panel.portfolio"
            ),
        ),
        migrations.AlterField(
            model_name="portfoliohonoraward",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="panel.portfolio"
            ),
        ),
        migrations.AlterField(
            model_name="portfoliointerest",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="panel.portfolio"
            ),
        ),
        migrations.AlterField(
            model_name="portfoliolanguage",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="panel.portfolio"
            ),
        ),
        migrations.AlterField(
            model_name="portfolioorganization",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="panel.portfolio"
            ),
        ),
        migrations.AlterField(
            model_name="portfoliopatent",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="panel.portfolio"
            ),
        ),
        migrations.AlterField(
            model_name="portfolioproject",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="panel.portfolio"
            ),
        ),
        migrations.AlterField(
            model_name="portfoliopublication",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="panel.portfolio"
            ),
        ),
        migrations.AlterField(
            model_name="portfoliorecommendation",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="panel.portfolio"
            ),
        ),
        migrations.AlterField(
            model_name="portfoliotestscore",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="panel.portfolio"
            ),
        ),
        migrations.AlterField(
            model_name="portfoliovolunteerwork",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="panel.portfolio"
            ),
        ),
        migrations.DeleteModel(
            name="PortfolioSite",
        ),
    ]
