# Generated by Django 4.2.4 on 2023-08-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("panel", "0003_portfolio_background_cover_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfoliocertification",
            name="starts_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="portfolioeducation",
            name="starts_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="portfolioexperience",
            name="starts_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="portfolioorganization",
            name="starts_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="portfolioproject",
            name="starts_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="portfoliovolunteerwork",
            name="starts_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
